export interface ProductItem {
  id: string;
  slug: string;
  title: string;
  titleAr: string;
  provider: string;
  providerCode: string;
  providerLogoText: string;
  providerLogoBg: string;
  providerLogoFg: string;
  chipBg: string;
  chipFg: string;
  type: 'Course' | 'Workshop' | 'Book' | 'Event' | 'Assessment';
  typeAr: string;
  shortDesc: string;
  shortDescAr: string;
  fullDesc: string;
  fullDescAr: string;
  priceEGP: number;
  duration: string;
  durationAr: string;
  rating: number;
  enrolled: number;
  thumbnailGradient: string;
  thumbnailIcon: string;
  paySlug: string;
  tags: string[];
  tagsAr: string[];
  syllabus: { title: string; desc: string }[];
  syllabusAr: { title: string; desc: string }[];
  whatIncluded: string[];
  whatIncludedAr: string[];
}

export const PRODUCTS_CATALOG: ProductItem[] = [
  {
    id: 'prod-1',
    slug: 'bootcamp-web',
    title: 'Full-Stack Web Engineering Bootcamp (12 Weeks)',
    titleAr: 'معسكر هندسة وتطوير الويب الشامل (١٢ أسبوع)',
    provider: 'StudyHub / TechBridge',
    providerCode: 'SH',
    providerLogoText: 'SH',
    providerLogoBg: '#E6EFEB',
    providerLogoFg: '#2E6F5E',
    chipBg: '#E6EFEB',
    chipFg: '#2E6F5E',
    type: 'Course',
    typeAr: 'دورة تدريبية مكثفة',
    shortDesc: 'Hands-on live engineering cohort covering React, Node.js, PostgreSQL, and payment architecture with 1-on-1 mentorship.',
    shortDescAr: 'معسكر تدريبي عملي مباشر يغطي React و Node.js وقواعد البيانات مع مشاريع تخرج واقعية ومتابعة فردية.',
    fullDesc: 'A rigorous 12-week program designed for aspiring software engineers. You will build enterprise-grade web applications from scratch, master TypeScript and Next.js, and integrate real payment gateways with automated webhooks.',
    fullDescAr: 'برنامج مكثف لمدة ١٢ أسبوعاً يؤهلك لسوق العمل الهندسي. تتعلم من خلاله بناء تطبيقات ويب متكاملة باستخدام TypeScript و Next.js وقواعد البيانات مع ربط بوابات الدفع الإلكتروني الحقيقية.',
    priceEGP: 4800,
    duration: '12 Weeks (Live)',
    durationAr: '١٢ أسبوع (مباشر)',
    rating: 4.9,
    enrolled: 310,
    thumbnailGradient: 'linear-gradient(135deg, #1E3A8A 0%, #3B82F6 100%)',
    thumbnailIcon: '💻',
    paySlug: 'sh-8k2m9q',
    tags: ['React', 'Next.js', 'PostgreSQL', 'Live Mentorship'],
    tagsAr: ['تطوير ويب', 'ريأكت', 'قواعد بيانات', 'مشاريع تخرج'],
    syllabus: [
      { title: 'Week 1-3: Modern TypeScript & React 19', desc: 'Component architecture, state managers, and custom hooks.' },
      { title: 'Week 4-7: Backend APIs & PostgreSQL', desc: 'Relational database schema design, indexing, and NestJS controllers.' },
      { title: 'Week 8-10: Payment Gateways & Webhooks', desc: 'Integrating Geidea, HMAC verification, and idempotency keys.' },
      { title: 'Week 11-12: Capstone Project & Hiring Pitch', desc: 'Deploying to cloud with Docker and simulated tech interviews.' },
    ],
    syllabusAr: [
      { title: 'الأسابيع ١-٣: أساسيات TypeScript و React 19', desc: 'هندسة المكونات وإدارة الحالة المتقدمة.' },
      { title: 'الأسابيع ٤-٧: بناء الخوادم وقواعد البيانات', desc: 'تصميم قواعد البيانات العلائقية ومحركات NestJS.' },
      { title: 'الأسابيع ٨-١٠: ربط بوابات الدفع والويب هوك', desc: 'الربط مع Geidea وفوري والتحقق الأمني من العمليات.' },
      { title: 'الأسابيع ١١-١٢: مشروع التخرج والجاهزية للتوظيف', desc: 'نشر المشروع سحابياً ومحاكاة المقابلات التقنية.' },
    ],
    whatIncluded: [
      'Live interactive video lectures 3x per week',
      'Private 1-on-1 weekly code review sessions',
      'Production-ready capstone codebase & GitHub review',
      'Accredited Course Completion Certificate',
    ],
    whatIncludedAr: [
      'محاضرات تفاعلية مباشرة ٣ مرات أسبوعياً',
      'جلسات مراجعة كود فردية أسبوعية مع مهندسين كبار',
      'مشروع تخرج واقعي يُضاف لمعرض أعمالك على GitHub',
      'شهادة إتمام معتمدة قابلة للتحقق الرقمي',
    ],
  },
  {
    id: 'prod-2',
    slug: 'grade-12-revision',
    title: 'Grade 12 Revision Series & Exam Prep',
    titleAr: 'سلسلة مراجعات الثانوية العامة والاختبارات التفاعلية',
    provider: 'Apex Classes',
    providerCode: 'AC',
    providerLogoText: 'AC',
    providerLogoBg: '#E8EEF7',
    providerLogoFg: '#2C5F9E',
    chipBg: '#E8EEF7',
    chipFg: '#2C5F9E',
    type: 'Course',
    typeAr: 'دورة دراسية معتمدة',
    shortDesc: 'Structured cohort review covering physics, mathematics, and exam techniques with weekly assessments and live tutor Q&A.',
    shortDescAr: 'مراجعة شاملة لمناهج الرياضيات والفيزياء مع بنوك أسئلة تفاعلية ومتابعة أسبوعية مباشرة مع كبار المدرسين.',
    fullDesc: 'Comprehensive preparation tailored to the Egyptian Thanawiya Amma curriculum. Combines question bank drill downs, model exam simulations, and instant performance analysis.',
    fullDescAr: 'مراجعة نهائية متكاملة لطلاب الثانوية العامة تشمل حل بنوك الأسئلة الوزارية، نماذج امتحانات مطابقة للاختبار النهائي، ومتابعة درجات دورية مع ولي الأمر.',
    priceEGP: 2400,
    duration: '6 Weeks Cohort',
    durationAr: '٦ أسابيع تفاعلية',
    rating: 4.8,
    enrolled: 620,
    thumbnailGradient: 'linear-gradient(135deg, #1E293B 0%, #475569 100%)',
    thumbnailIcon: '📐',
    paySlug: 'ac-9w3e5z',
    tags: ['Physics', 'Pure Math', 'Question Banks', 'Live Q&A'],
    tagsAr: ['فيزياء', 'رياضيات', 'بنوك أسئلة', 'بث مباشر'],
    syllabus: [
      { title: 'Module 1: Mechanics & Calculus Foundations', desc: 'Intensive problem solving and speed drilling.' },
      { title: 'Module 2: Electromagnetism & Modern Physics', desc: 'Conceptual mastery and high-yield question patterns.' },
      { title: 'Module 3: Full-Length Timed Exam Simulations', desc: 'Automated scoring with individualized weakness reports.' },
    ],
    syllabusAr: [
      { title: 'الوحدة الأولى: الميكانيكا وحساب التفاضل', desc: 'حل تدريبات مكثفة وتدريب على سرعة الحل في الامتحان.' },
      { title: 'الوحدة الثانية: الكهربية والفيزياء الحديثة', desc: 'فهم المفاهيم المعقدة ونماذج الأسئلة المتكررة.' },
      { title: 'الوحدة الثالثة: امتحانات شاملة محاكية للاختبار', desc: 'تصحيح إلكتروني فوري مع تقرير بنقاط القوة والضعف.' },
    ],
    whatIncluded: [
      'Printed revision booklets delivered to your address',
      'Access to 2,500+ interactive graded practice questions',
      'Weekly live problem-solving webinars',
      'Parent progress dashboard & WhatsApp updates',
    ],
    whatIncludedAr: [
      'مذكرات المراجعة المطبوعة تصل إلى منزلك',
      'صلاحية دخول لبنك أسئلة يضم أكثر من ٢٥٠٠ سؤال محلول',
      'بث مباشر أسبوعي للإجابة على جميع الاستفسارات',
      'لوحة متابعة لولي الأمر وإشعارات واتساب أسبوعية',
    ],
  },
  {
    id: 'prod-3',
    slug: 'elhesa-assessment-pass',
    title: 'Gamified Learning & Skill Assessment Pass',
    titleAr: 'باقة التقييم التفاعلي واشتراك منصة الحصة',
    provider: 'منصة الحصة (EL HESA)',
    providerCode: 'EH',
    providerLogoText: 'EH',
    providerLogoBg: '#FBF3E0',
    providerLogoFg: '#B8860B',
    chipBg: '#FBF3E0',
    chipFg: '#B8860B',
    type: 'Assessment',
    typeAr: 'تقييم وتدريب تفاعلي',
    shortDesc: 'Gamified Egyptian K-12 learning pass with micro-quizzes, automated badges, and performance diagnostics.',
    shortDescAr: 'اشتراك منصة الحصة التعليمية التفاعلية مع بنك الأسئلة المُميع وتشخيص فوري لمستوى الطالب.',
    fullDesc: 'Unlimited access to the EL HESA gamified platform. Students unlock learning stages, earn skill badges, and benchmark their progress against thousands of peers across Egypt.',
    fullDescAr: 'اشتراك غير محدود في منصة الحصة التفاعلية. يجتاز الطالب مراحل وتحديات تعليمية ممتعة ويكتسب أوسمة الإتقان مع قياس دقيق لتطوره الأكاديمي.',
    priceEGP: 600,
    duration: 'Full Term Access',
    durationAr: 'متاح طوال الفصل الدراسي',
    rating: 4.9,
    enrolled: 1450,
    thumbnailGradient: 'linear-gradient(135deg, #D97706 0%, #F59E0B 100%)',
    thumbnailIcon: '🏆',
    paySlug: 'eh-2n6b8v',
    tags: ['Gamification', 'Quizzes', 'Badges', 'Diagnostics'],
    tagsAr: ['تعليم تفاعلي', 'اختبارات قصيرة', 'أوسمة وجوائز', 'تشخيص فوري'],
    syllabus: [
      { title: 'Phase 1: Baseline Diagnostic Assessment', desc: 'Pinpoint knowledge gaps across core competencies.' },
      { title: 'Phase 2: Adaptive Practice Quests', desc: 'Questions automatically adjust in difficulty to learner mastery.' },
      { title: 'Phase 3: National Leaderboards & Challenges', desc: 'Compete in weekly timed sprints with community rewards.' },
    ],
    syllabusAr: [
      { title: 'المرحلة الأولى: التقييم التشخيصي المبدئي', desc: 'تحديد الفجوات المعرفية ومستوى الطالب بدقة.' },
      { title: 'المرحلة الثانية: رحلات تدريبية ذكية', desc: 'تتغير صعوبة الأسئلة تلقائياً بحسب إجابات الطالب واستيعابه.' },
      { title: 'المرحلة الثالثة: لوحة المتصدرين وتحديات نهاية الأسبوع', desc: 'منافسات مشوقة مع زملاء الدراسة بجوائز رمزية.' },
    ],
    whatIncluded: [
      'Full-term access to EL HESA interactive web & mobile app',
      'Automated parent diagnostic reports sent bi-weekly',
      'Digital completion badges and student ranking profile',
    ],
    whatIncludedAr: [
      'اشتراك كامل طوال الفصل الدراسي عبر الموبايل والويب',
      'تقارير دورية تُرسل لولي الأمر كل أسبوعين عبر الواتساب',
      'أوسمة تفاعلية وشهادات تقدير شهرية للطلاب المتفوقين',
    ],
  },
  {
    id: 'prod-4',
    slug: 'cv-career-workshop',
    title: 'CV Optimization & Tech Handover Workshop',
    titleAr: 'ورشة عمل صياغة السيرة الذاتية والجاهزية الوظيفية',
    provider: 'Career Hub',
    providerCode: 'CH',
    providerLogoText: 'CH',
    providerLogoBg: '#F0EAF7',
    providerLogoFg: '#7A4CA0',
    chipBg: '#F0EAF7',
    chipFg: '#7A4CA0',
    type: 'Workshop',
    typeAr: 'ورشة عمل تدريبية',
    shortDesc: 'Interactive workshop on portfolio presentation, technical interviews, and salary negotiation for tech specialists.',
    shortDescAr: 'ورشة تدريبية مكثفة للمتخصصين في التكنولوجيا لتجهيز معرض الأعمال واجتياز المقابلات التقنية باحترافية.',
    fullDesc: 'Get your CV and portfolio reviewed line-by-line by engineering hiring managers. Learn how to highlight high-impact contributions, pass ATS screening filters, and negotiate market-rate offers.',
    fullDescAr: 'مراجعة دقيقة لملفك وسيرتك الذاتية مع مديري توظيف تقنيين. تتعلم كيف تتجاوز أنظمة فلترة الـ ATS وتصيغ مشاريعك بلغة الأرقام وتتفاوض على الراتب بثقة.',
    priceEGP: 350,
    duration: '1 Day Intensive',
    durationAr: 'يوم تدريبي مكثف (٤ ساعات)',
    rating: 4.7,
    enrolled: 480,
    thumbnailGradient: 'linear-gradient(135deg, #581C87 0%, #9333EA 100%)',
    thumbnailIcon: '💼',
    paySlug: 'ch-5t8o2p',
    tags: ['CV Review', 'ATS Friendly', 'Portfolio', 'Salary Prep'],
    tagsAr: ['سيرة ذاتية', 'تخطي ATS', 'بورتفوليو', 'استعداد للمقابلات'],
    syllabus: [
      { title: 'Session 1: The ATS-Proof Tech Resume', desc: 'Action verbs, metric-driven achievements, and clean formatting.' },
      { title: 'Session 2: GitHub & Portfolio Architecture', desc: 'Showcasing real deployment links and architecture blueprints.' },
      { title: 'Session 3: Live Mock Interview Breakdown', desc: 'Behavioral and system design answering strategies.' },
    ],
    syllabusAr: [
      { title: 'الجلسة الأولى: كتابة سيرة ذاتية تتخطى أنظمة ATS', desc: 'صياغة الإنجازات بلغة الأرقام والتنسيق المتوافق مع الشركات.' },
      { title: 'الجلسة الثانية: تنسيق معرض الأعمال على GitHub', desc: 'عرض الروابط التجريبية الحية وتوثيق المشاريع باحتراف.' },
      { title: 'الجلسة الثالثة: محاكاة مقابلة عمل مباشرة', desc: 'أفضل الطرق للإجابة على الأسئلة التقنية والشخصية.' },
    ],
    whatIncluded: [
      'Line-by-line personalized CV critique via email',
      'Downloadable modern Notion & LaTeX CV templates',
      'Recording of the 4-hour live workshop session',
    ],
    whatIncludedAr: [
      'مراجعة وتعديل مخصص لسيرتك الذاتية من متخصص توظيف',
      'قوالب سيرة ذاتية جاهزة بصيغ Notion و Word و LaTeX',
      'تسجيل كامل لورشة العمل ومكتبة مصادر إضافية',
    ],
  },
  {
    id: 'prod-5',
    slug: 'aws-cloud-prep',
    title: 'AWS Cloud Practitioner Prep Lab',
    titleAr: 'المعمل التدريبي لاجتياز شهادة AWS Cloud العالمية',
    provider: 'StudyHub Tech',
    providerCode: 'SH',
    providerLogoText: 'SH',
    providerLogoBg: '#E6EFEB',
    providerLogoFg: '#2E6F5E',
    chipBg: '#E6EFEB',
    chipFg: '#2E6F5E',
    type: 'Course',
    typeAr: 'شهادة مهنية دولية',
    shortDesc: 'Official AWS Cloud exam preparation course with practice exams, cloud sandbox labs, and certified tutor coaching.',
    shortDescAr: 'كورس إعداد متقدم لشهادة الحوسبة السحابية من أمازون مع معامل تطبيقية وامتحانات تجريبية مماثلة للاختبار الدولي.',
    fullDesc: 'Prepare to pass the AWS Certified Cloud Practitioner (CLF-C02) exam on your first attempt. Includes dedicated sandbox cloud environments to practice provisioning S3 buckets, EC2 instances, and VPC security groups.',
    fullDescAr: 'استعد لاجتياز اختبار أمازون السحابي المعتمد دولياً من أول محاولة. يشمل بيئة سحابية تطبيقية لتجربة خدمات S3 و EC2 وقواعد بيانات RDS مع أسئلة امتحانات سابقة.',
    priceEGP: 1800,
    duration: '4 Weeks Lab',
    durationAr: '٤ أسابيع معامل واختبارات',
    rating: 4.9,
    enrolled: 215,
    thumbnailGradient: 'linear-gradient(135deg, #065F46 0%, #10B981 100%)',
    thumbnailIcon: '☁️',
    paySlug: 'sh-4r7t1a',
    tags: ['AWS', 'Cloud', 'Sandbox Labs', 'Exam Prep'],
    tagsAr: ['حوسبة سحابية', 'أمازون AWS', 'معامل تطبيقية', 'امتحانات سابقة'],
    syllabus: [
      { title: 'Week 1: Cloud Concepts & Security Shared Model', desc: 'IAM roles, MFA policies, and compliance standards.' },
      { title: 'Week 2: Compute & Storage Services', desc: 'Deploying EC2, Lambda functions, and S3 lifecycle rules.' },
      { title: 'Week 3: Networking & High Availability', desc: 'VPCs, Subnets, Route 53, and Load Balancers.' },
      { title: 'Week 4: Billing, Pricing & Timed Exam Drills', desc: '3 full-length 65-question practice exam simulations.' },
    ],
    syllabusAr: [
      { title: 'الأسبوع الأول: مفاهيم السحابة ونموذج الأمان المشترك', desc: 'إدارة الصلاحيات عبر IAM ومعايير الحماية.' },
      { title: 'الأسبوع الثاني: خدمات المعالجة والتخزين', desc: 'تشغيل خوادم EC2 ودوال Lambda وتخزين S3.' },
      { title: 'الأسبوع الثالث: الشبكات وتوزيع الأحمال', desc: 'بناء شبكات VPC وربط نطاقات Route 53 وموزع الأحمال.' },
      { title: 'الأسبوع الرابع: الفوترة ونماذج الامتحانات النهائية', desc: 'حل ٣ امتحانات تجريبية كاملة بنظام التوقيت الدولي.' },
    ],
    whatIncluded: [
      '4 weeks of guided cloud sandbox environment access',
      '3 full-length timed mock exams with explanations',
      'Study notes cheat sheet for quick exam day revision',
    ],
    whatIncludedAr: [
      'بيئة سحابية تطبيقية على AWS للتجربة طوال ٤ أسابيع',
      '٣ امتحانات تجريبية كاملة مع شرح تفصيلي لكل إجابة',
      'ملخص مركز وشامل لأهم مصطلحات الاختبار للمراجعة السريعة',
    ],
  },
  {
    id: 'prod-6',
    slug: 'creator-studio-masterclass',
    title: 'Digital Creator Studio Masterclass',
    titleAr: 'ماستركلاس صناعة المحتوى المرئي والإعلانات',
    provider: 'Sidekick Media Lab',
    providerCode: 'SK',
    providerLogoText: 'SK',
    providerLogoBg: '#FBEBE9',
    providerLogoFg: '#D10721',
    chipBg: '#FBEBE9',
    chipFg: '#D10721',
    type: 'Workshop',
    typeAr: 'ورشة عمل تطبيقية',
    shortDesc: 'Master mobile video shooting, viral hooks scripting, lighting setups, and CapCut/Premiere editing for social creators.',
    shortDescAr: 'ماستركلاس عملي في تصوير فيديوهات السوشيال ميديا، كتابة الإسكربتات الجاذبة، وضبط الإضاءة والمونتاج السريع.',
    fullDesc: 'A weekend studio intensive led by Sidekick creative directors. Bring your smartphone or camera and produce 3 polished vertical video assets ready to publish on TikTok, Instagram, and YouTube Shorts.',
    fullDescAr: 'تدريب عملي داخل الاستوديو خلال عطلة نهاية الأسبوع بقيادة مخرجي Sidekick. تتعلم كيفية صناعة فيديوهات قصيرة احترافية تحقق انتشاراً واسعاً على إنستغرام وتيك توك.',
    priceEGP: 3200,
    duration: '2 Days Weekend',
    durationAr: 'يومان خلال عطلة نهاية الأسبوع',
    rating: 5.0,
    enrolled: 180,
    thumbnailGradient: 'linear-gradient(135deg, #991B1B 0%, #EF4444 100%)',
    thumbnailIcon: '🎬',
    paySlug: 'sk-media-prod',
    tags: ['Reels', 'TikTok Ads', 'Lighting & Audio', 'Editing'],
    tagsAr: ['فيديوهات ريلز', 'إعلانات تيك توك', 'إضاءة وصوت', 'مونتاج'],
    syllabus: [
      { title: 'Day 1: Viral Scripting & Studio Lighting', desc: 'The 3-second hook rule, ring light vs 3-point lighting setups.' },
      { title: 'Day 2: Fast Mobile Editing & Color Grading', desc: 'Audio soundscapes, dynamic zooms, keyframe animations.' },
    ],
    syllabusAr: [
      { title: 'اليوم الأول: كتابة الإسكربت وضبط إضاءة الاستوديو', desc: 'قاعدة أول ٣ ثوانٍ الجاذبة، وهندسة الصوت للهواتف.' },
      { title: 'اليوم الثاني: المونتاج السريع وتصحيح الألوان', desc: 'إضافة المؤثرات الصوتية والانتقالات الديناميكية.' },
    ],
    whatIncluded: [
      'Live in-studio shooting access with professional gear',
      'Sidekick library of 50+ viral hook scripts and sound effects',
      'Personal critique on your 3 completed video edits',
    ],
    whatIncludedAr: [
      'حضور عملي في الاستوديو مع معدات التصوير والإضاءة',
      'مكتبة Sidekick تضم أكثر من ٥٠ فكرة وسيناريو إعلاني جاهز',
      'تقييم وتعديل تفصيلي لـ ٣ فيديوهات تقوم بتصويرها في الورشة',
    ],
  },
  {
    id: 'prod-7',
    slug: 'ecommerce-playbook',
    title: 'The Egyptian E-Commerce Playbook & Financial Models',
    titleAr: 'دليل التجارة الإلكترونية المصرية ونماذج الحسابات المالية',
    provider: 'bldr Publishing',
    providerCode: 'BM',
    providerLogoText: 'BP',
    providerLogoBg: '#F1F3F5',
    providerLogoFg: '#212529',
    chipBg: '#F1F3F5',
    chipFg: '#212529',
    type: 'Book',
    typeAr: 'كتاب ودليل عملي',
    shortDesc: 'Complete 180-page strategic handbook with ready-to-use Excel unit economics models, shipping negotiation scripts, and ad ROAS benchmarks.',
    shortDescAr: 'دليل استراتيجي شامل من ١٨٠ صفحة مع نماذج إكسيل لاقتصاديات المتجر، نصوص التفاوض مع شركات الشحن، ومؤشرات الربحية.',
    fullDesc: 'Written by bldr studio partners based on real metrics from Egyptian direct-to-consumer and B2B ventures. Covers delivery cash-on-delivery mitigation, payment gateway fee optimization, and high-margin supplier sourcing.',
    fullDescAr: 'كتاب استراتيجي وعملي من شركاء bldr مستند إلى أرقام وتجارب حقيقية في السوق المصري. يغطي حلول مشكلات الدفع عند الاستلام، خفض نسبة المرتجعات، وحساب تكلفة الاستحواذ بدقة.',
    priceEGP: 850,
    duration: 'Instant Digital Download',
    durationAr: 'تحميل رقمي فوري (PDF + Excel)',
    rating: 4.9,
    enrolled: 890,
    thumbnailGradient: 'linear-gradient(135deg, #111827 0%, #374151 100%)',
    thumbnailIcon: '📖',
    paySlug: 'bm-consult-sess',
    tags: ['E-Commerce', 'Financial Model', 'COD Solutions', 'Handbook'],
    tagsAr: ['تجارة إلكترونية', 'نماذج مالية', 'حلول الشحن', 'دليل شامل'],
    syllabus: [
      { title: 'Chapter 1: Market Sizing & Egyptian Consumer Behavior', desc: 'Payment preferences and checkout drop-off triggers.' },
      { title: 'Chapter 2: Managing Return Rates & Courier SLAs', desc: 'WhatsApp verification automations that cut returns by 35%.' },
      { title: 'Chapter 3: The Plug-and-Play Unit Economics Model', desc: 'Pre-built formulas for CAC, LTV, contribution margins.' },
    ],
    syllabusAr: [
      { title: 'الفصل الأول: سلوك المستهلك المصري وتفضيلات الدفع', desc: 'كيف يتخذ المشتري قراره ولماذا يتخلى عن سلة الشراء.' },
      { title: 'الفصل الثاني: تقليل المرتجعات وإدارة شركات الشحن', desc: 'أنظمة تأكيد الطلب التلقائية التي تخفض المرتجعات بنسبة ٣٥٪.' },
      { title: 'الفصل الثالث: النموذج المالي الشامل لاقتصاديات المتجر', desc: 'معادلات إكسيل جاهزة لحساب هامش الربح وتكلفة الإعلانات.' },
    ],
    whatIncluded: [
      'Comprehensive 180-page DRM-free PDF Handbook',
      'Fully editable Excel / Google Sheets financial forecast model',
      'Supplier contract templates & courier negotiation scripts',
    ],
    whatIncludedAr: [
      'كتاب إلكتروني PDF كامل من ١٨٠ صفحة عالي الدقة',
      'نموذج إكسيل مالي شامل وجاهز للتعديل المباشر لمشروعك',
      'نماذج عقود الموردين ونصوص التفاوض مع شركات التوصيل',
    ],
  },
  {
    id: 'prod-8',
    slug: 'fintech-summit-pass',
    title: 'FinTech Founders & Venture Scaling Summit Pass',
    titleAr: 'تذكرة قمة مؤسسي التكنولوجيا المالية وتوسع المشاريع',
    provider: 'Tech House / bldr',
    providerCode: 'TH',
    providerLogoText: 'TH',
    providerLogoBg: '#E8F5FE',
    providerLogoFg: '#0066CC',
    chipBg: '#E8F5FE',
    chipFg: '#0066CC',
    type: 'Event',
    typeAr: 'فعالية ومؤتمر سنوي',
    shortDesc: 'A full-day executive gathering in New Cairo featuring Central Bank of Egypt regulatory panels, gateway demos, and private networking.',
    shortDescAr: 'ملتقى تنفيذي لمدة يوم كامل في القاهرة الجديدة يناقش تشريعات المدفوعات وبوابات الدفع مع جلسات تعارف وشراكات استثمارية.',
    fullDesc: 'Join 250+ venture operators, FinTech executives, and founders. Experience live demonstrations of the bldr payment engine, attend keynotes on Egyptian e-payments expansion, and connect with venture capital partners.',
    fullDescAr: 'اجمع بين أكثر من ٢٥٠ رائد أعمال ومستثمر في قطاع التكنولوجيا المالية. يتضمن الملتقى استعراضاً مباشراً لأحدث حلول الدفع الرقمي وجلسات تواصل حصرية مع صناديق رأس المال الجريء.',
    priceEGP: 1500,
    duration: 'Full Day Pass (Cairo)',
    durationAr: 'يوم كامل (التجمع الخامس، القاهرة)',
    rating: 5.0,
    enrolled: 195,
    thumbnailGradient: 'linear-gradient(135deg, #0F172A 0%, #0284C7 100%)',
    thumbnailIcon: '🎟️',
    paySlug: 'th-gateway-int',
    tags: ['FinTech', 'Summit', 'Networking', 'Executive Pass'],
    tagsAr: ['تكنولوجيا مالية', 'مؤتمر', 'شبكة علاقات', 'تذكرة تنفيذية'],
    syllabus: [
      { title: 'Morning: Keynotes on Egypt E-Payment Innovations', desc: 'InstaPay, Meeza, and CBE regulatory sandboxes.' },
      { title: 'Mid-Day: Technical Masterclasses', desc: 'PCI-DSS compliance, HMAC security, and unified checkout.' },
      { title: 'Evening: Private VIP Investor & Founder Lounge', desc: 'Cocktail networking and 1-on-1 venture deal flow discussions.' },
    ],
    syllabusAr: [
      { title: 'الفترة الصباحية: كلمات رئيسية حول مستقبل المدفوعات', desc: 'تطور إنستاباي، بطاقات ميزة، وتشريعات البنك المركزي.' },
      { title: 'الفترة المسائية: ورش عمل تقنية متقدمة', desc: 'معايير أمان PCI-DSS، التشفير الرقمي، وتكامل الأنظمة.' },
      { title: 'الختام: جلسة تعارف خاصة مع المستثمرين والشركاء', desc: 'لقاءات عمل مباشرة وبحث فرص التمويل والشراكات الاستراتيجية.' },
    ],
    whatIncluded: [
      'Full-day badge with access to all panels and workshops',
      'Catered executive lunch and artisan coffee breaks',
      'Access to the private attendee networking portal',
    ],
    whatIncludedAr: [
      'تذكرة دخول كاملة لجميع الجلسات وورش العمل طوال اليوم',
      'غداء عمل وبوفيه مفتوح مع استراحات القهوة طوال الفعالية',
      'صلاحية دخول لمنصة التواصل والتشبيك الرقمي بين الحضور',
    ],
  },
];
